version: '3.7'

services:
  frontend-apollo:
    build:
      context: ./frontend-apollo
      dockerfile: ./Dockerfile
    container_name: frontend-apollo
    command: npm run start
    volumes:
      - ./frontend-apollo:/app:cached
      - frontend-apollo-npm-data:/app/node_modules
      - ../.:/app/package
    ports:
      - 3001:3001
  frontend-relay:
    build:
      context: ./frontend-relay
      dockerfile: ./Dockerfile
    container_name: frontend-relay
    command: npm run start
    volumes:
      - ./frontend-relay:/app:cached
      - frontend-relay-npm-data:/app/node_modules
    ports:
      - 3002:3002
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    command: node index.js
    volumes:
      - ./backend:/app:cached
      - backend-npm-data:/app/node_modules
    ports:
      - 4000:4000

volumes:
  frontend-apollo-npm-data:
    driver: local
  frontend-relay-npm-data:
    driver: local
  backend-npm-data:
    driver: local
